attendance-war/src/java/com/plusnet/managedbean/CourseManagedBean.java
package com.attendance.managedbean;

import com.attendance.entity.Course;
import com.attendance.facade.CourseFacade;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean
@SessionScoped
public class CourseManagedBean implements Serializable {

    @EJB
    private CourseFacade courseFacade;
    private Course course;
    private List<Course> courseList;

    public CourseManagedBean() {
        course = new Course();
    }

    public void createCourse() {
        courseFacade.create(course);
        course = new Course();
    }

    public List<Course> getCourses() {
        return courseList = courseFacade.findAll();
    }

    public void editCourse(Course c) {
        courseFacade.edit(course);
        course = new Course();
    }

    public void deleteCourse(Course course) {
        courseFacade.remove(course);
    }

    public int courseCount() {
        return courseFacade.count();
    }

    public int getByLanguage(int languageCode) {
        return courseFacade.getByLanguage(languageCode);
    }

    public String getMostPopulatedCourseName(String popularity) {
        String courseName = courseFacade.getMostPopulatedCourseName(popularity);
        return courseName;
    }
    
    public long getMostPopulatedCourseCount(String popularity) {
        long count = courseFacade.getMostPopulatedCourseCount(popularity);
        return count;
    }
    
    public long getCourseCountByLevel(String level) {
        return courseFacade.getCourseCountByLevel(level);
    }

    // GETTERS & SETTERS
    public Course getCourse() {
        return course;
    }

    public CourseFacade getCourseFacade() {
        return courseFacade;
    }

    public List<Course> getCourseList() {
        return courseList;
    }

    public void setCourse(Course course) {
        this.course = course;
    }

    public void setCourseFacade(CourseFacade courseFacade) {
        this.courseFacade = courseFacade;
    }

    public void setCourseList(List<Course> courseList) {
        this.courseList = courseList;
    }
}

attendance-war/web/attendance.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f='http://java.sun.com/jsf/core'
      xmlns:p="http://primefaces.org/ui">

    <h:head>
        <title>Närvaro Lista</title>
    </h:head>
    <h:body>
        <ui:include src="header.xhtml"/><br></br>

        <h:form id="form" style="width: 900px; margin: auto">
            <p:panel id="panel" header="Närvaro Lista. Var god och välja en kurs" style="margin-bottom:20px;">
                <h:panelGrid columns="4" cellpadding="5" style="margin: auto;">
                    <h:outputLabel for="course_name" value="Välj en kurs: *" />
                    <h:selectOneMenu id="course_name" value="#{attendanceManagedBean.courseName}" required="true" label="Kursnamn">
                        <f:selectItem itemLabel="Välj här" itemValue="" noSelectionOption="true" />
                        <f:selectItem itemLabel="Javautvecklare" itemValue="Javautvecklare" />
                        <f:selectItem itemLabel="Sharepoint utvecklare" itemValue="Sharepoint utvecklare" />
                        <f:selectItem itemLabel="Automationsingenjör" itemValue="Automationsingenjör" />
                        <f:selectItem itemLabel="Agil projektledare" itemValue="Agil projektledare" />
                        <f:selectItem itemLabel="Drift- &amp; fastighetstekniker" itemValue="Drift- &amp; fastighetstekniker" />
                        <f:selectItem itemLabel="Kvalitetssäkrare och testare inom IT" itemValue="Kvalitetssäkrare och testare inom IT" />
                        <f:selectItem itemLabel="Systemutvecklare .NET" itemValue="Systemutvecklare .NET" />
                        <f:selectItem itemLabel="Verktygsmakare" itemValue="Verktygsmakare" />
                    </h:selectOneMenu>
                    <p:commandButton update="@form"  action="#{attendanceManagedBean.getStudentsByCourseName()}" value="Visa Studenter" />
                </h:panelGrid>
            </p:panel>

            <p:dataTable id="checkbox" var="student" value="#{attendanceManagedBean.studentListByCourseName}" 
                         selection="#{attendanceManagedBean.attendants}" rowKey="#{student.id}" style="margin-bottom:20px;">

                <f:facet name="header">
                    Student List
                </f:facet>
                <p:column selectionMode="multiple" style="width: 16px; text-align:center;"/>
                <p:column headerText="Förstnamn">
                    <h:outputText value="#{student.firstName}" />
                </p:column>
                <p:column headerText="Efternamn">
                    <h:outputText value="#{student.lastName}" />
                </p:column>
                <p:column headerText="Email">
                    <h:outputText value="#{student.email}" />
                </p:column>
                <f:facet name="footer">
                    <p:commandButton actionListener="#{attendanceManagedBean.dateControlForCourse()}" resetValues="true"
                                     update="@form" icon="ui-icon-disk" value="Spara" />
                </f:facet>
            </p:dataTable>

            <p:messages id="messages" showDetail="true" autoUpdate="true" closable="true" />

            <p:dataTable id="attendanceLista" rendered="#{not empty attendanceManagedBean.jmsContents}" 
                         var="attendant" value="#{attendanceManagedBean.jmsContents}" style="margin-bottom: 30px !important;">
                <f:facet name="header">
                    Närvaro lista för studenter
                </f:facet>
                <p:column headerText="Student Namn">
                    <h:outputText value="#{attendant.studentName}" />
                </p:column>
                <p:column headerText="Email">
                    <h:outputText value="#{attendant.studentEmail}" />
                </p:column>
                <p:column headerText="Kursnamn" style="width: 250px;">
                    <h:outputText value="#{attendant.courseName}" />
                </p:column>
                <p:column headerText="Datum" style="width: 90px;">
                    <h:outputText value="#{attendant.date}" >
                        <f:convertDateTime pattern="yyyy-MM-dd"/>
                    </h:outputText>
                </p:column>

                <f:facet name="footer">
                    <p:commandButton action="#{attendanceManagedBean.sendJMS()}" 
                                     update="@form" icon="ui-icon-mail-closed" value="Skicka Rapport" />
                </f:facet>
            </p:dataTable>

        </h:form>
    </h:body>
</html>

attendance-war/web/course.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f='http://java.sun.com/jsf/core'
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Registrera ny student</title>
    </h:head>
    <h:body>
        <ui:include src="header.xhtml"/><br></br>

        <!-- Register form -->
        <p:layout id="layout" styleClass="reg-student-layout">
            <p:layoutUnit id="layoutRegister" position="west" resizable="false" size="210">
                <h:form id="registerForm" style="margin-left: 5px;">
                    <br/><p:outputLabel class="ui-state-default" style="font-size: 18px; padding: 5px 15px;" value="Registrera ny kurs"/>
                    <br/>
                    <br/><h:outputText value="Kursnamn" styleClass="form_label"/><h:message for="course_name" styleClass="error"/>
                    <br/><p:inputText style="margin: auto;" id="course_name" value="#{courseManagedBean.course.courseName}"/>

                    <h:outputText value="Kurskod" styleClass="form_label"/><h:message for="course_code" styleClass="error" />
                    <br/><p:inputText style="margin: auto;" id="course_code" value="#{courseManagedBean.course.courseCode}"/>

                    <h:outputText value="Kursspråk" styleClass="form_label"/><h:message for="course_language" styleClass="error" />
                    <br/><p:inputText style="margin: auto;" id="course_language" value="#{courseManagedBean.course.courseLanguage}"/>

                    <h:outputText value="Kursnivå" styleClass="form_label"/><h:message for="course_level" styleClass="error" />
                    <br/>
                    <p:selectOneMenu id="course_level" style="width: 95%" value="#{courseManagedBean.course.courseLevel}">
                        <f:selectItem itemLabel="Välj kursnivå" itemValue="" />
                        <f:selectItem itemLabel="Grund" itemValue="Grundnivå" />
                        <f:selectItem itemLabel="Avancerad" itemValue="Avancerad" />
                    </p:selectOneMenu>

                    <br/><h:outputText value="Ansvarig" styleClass="form_label"/><h:message for="responsible" styleClass="error" />
                    <br/><p:inputText style="margin: auto;" id="responsible" value="#{courseManagedBean.course.responsible}"/>

                    <br/><br/><p:commandButton id="submit" value="Skapa Kurs" update="registerForm, :tableForm:dataTable"
                                         style="width: 95%" actionListener="#{courseManagedBean.createCourse()}" />
                </h:form>
            </p:layoutUnit>

            <!-- Output form -->
            <p:layoutUnit id="layoutTable" position="center">
                <h:form style="margin-left: 5px;" id="tableForm">
                    <p:dataTable id="dataTable" value="#{courseManagedBean.getCourses()}" 
                                 var="course" >

                        <p:column style="width: 250px">
                            <f:facet name="header">Kursnamn</f:facet>
                            <p:outputLabel value="#{course.courseName}"/>
                        </p:column>

                        <p:column>
                            <f:facet name="header">Kurskod</f:facet>
                            <p:outputLabel value="#{course.courseCode}"/>
                        </p:column>

                        <p:column>
                            <f:facet name="header">Kursspråk</f:facet>
                            <p:outputLabel value="#{course.courseLanguage}"/>
                        </p:column>

                        <p:column>
                            <f:facet name="header">Kursnivå</f:facet>
                            <p:outputLabel value="#{course.courseLevel}"/>
                        </p:column>

                        <p:column>
                            <f:facet name="header">Ansvarig</f:facet>
                            <p:outputLabel value="#{course.responsible}"/>
                        </p:column>

                        <p:column style="width:5%; text-align: center;">
                            <f:facet name="header">Edit</f:facet>
                            <p:commandLink value="edit" type="button" 
                                           action="#{courseManagedBean.setCourse(course)}"
                                           update=":update" oncomplete="PF('update').show();"/>
                        </p:column>

                        <p:column style="width:8%; text-align: center;">
                            <f:facet name="header">Ta bort</f:facet>
                            <p:commandLink value="delete" update="@form" 
                                           action="#{courseManagedBean.deleteCourse(course)}"/>
                        </p:column>
                    </p:dataTable>
                </h:form>
            </p:layoutUnit>
            
            
            <!-- Update Modal -->
            <p:dialog id="update" closable="false" header="Updatera Kurs" widgetVar="update" modal="true" height="300" visible="#{facesContext.validationFailed}">
                <h:form id="updateForm">   
                    <h:outputText value="Kursnamn" styleClass="form_label"/><h:message for="c_name" styleClass="error"/>
                    <br><p:inputText style="margin: auto;" id="c_name" value="#{courseManagedBean.course.courseName}"/></br>

                    <h:outputText value="Kurskod" styleClass="form_label"/><h:message for="c_code" styleClass="error" />
                    <br><p:inputText style="margin: auto;" id="c_code" value="#{courseManagedBean.course.courseCode}"/></br>

                    <h:outputText value="Kursspråk" styleClass="form_label"/><h:message for="c_language" styleClass="error" />
                    <br><p:inputText style="margin: auto;" id="c_language" value="#{courseManagedBean.course.courseLanguage}"/></br>

                    <h:outputText value="Kursnivå" styleClass="form_label"/><h:message for="c_level" styleClass="error" />
                    <br><p:inputText style="margin: auto;" id="c_level" value="#{courseManagedBean.course.courseLevel}"/></br>

                    <h:outputText value="Ansvarig" styleClass="form_label"/><h:message for="c_responsible" styleClass="error" />
                    <br><p:inputText style="margin: auto;" id="c_responsible" value="#{courseManagedBean.course.responsible}"/></br>

                    <br><p:commandButton id="updateButton" value="Updatera" update=":tableForm:dataTable" 
                                         action="#{courseManagedBean.editCourse(course)}" style="width: 100%"
                                         onclick="if (args &amp;&amp; !args.validationFailed) editDialog.hide()" /></br>
                </h:form>
            </p:dialog>
        </p:layout>
    </h:body>
</html>

attendance-war/web/header.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p='http://primefaces.org/ui'>

    <h:outputStylesheet library="css" name="style.css" />

    <h:form>  
        <p:menubar>
            <p:menuitem value="Hemsida" url="index.xhtml" icon="ui-icon-home" />
            <p:menuitem value="Student" url="student.xhtml" icon="ui-icon-document"/>
            <p:menuitem value="Kurser" url="course.xhtml" icon="ui-icon-pencil" />
            <p:menuitem value="Närvaro Lista" url="attendance.xhtml" icon="ui-icon-calendar"/>

            <f:facet name="options">
                <p:commandButton type="submit" value="Logout (#{teacherManagedBean.teacher.userName})" 
                                 action="#{teacherManagedBean.logout()}"
                                 icon="ui-icon-extlink" />
            </f:facet>
        </p:menubar>
    </h:form>
</ui:composition>

attendance-war/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Admin Console</title>
    </h:head>
    <h:body>
        <ui:include src="header.xhtml"/>
        <br />
        <p:layout styleClass="stat-layout">
            <p:layoutUnit position="center">
                <p:panelGrid columns="2" styleClass="stat-panel">
                    <f:facet name="header">
                        <h3>Student &amp; Kurs Statistiker</h3>
                    </f:facet>

                    <h:outputText value="Antal studenter" />
                    <h:outputText value="#{studentManagedBean.studentCount()}" />

                    <h:outputText value="Antal kurser" />
                    <h:outputText value="#{courseManagedBean.courseCount()}" />

                    <h:outputText value="Mest populära kurs" />
                    <h:outputText value="#{courseManagedBean.getMostPopulatedCourseName('DESC')}" />
                    
                    <h:outputText value="Antal studenter på mest populära kursen" />
                    <h:outputText value="#{courseManagedBean.getMostPopulatedCourseCount('DESC')}" />

                    <h:outputText value="Minst populära kurs" />
                    <h:outputText value="#{courseManagedBean.getMostPopulatedCourseName('ASC')}" />
                    
                    <h:outputText value="Antal studenter på minst populära kursen" />
                    <h:outputText value="#{courseManagedBean.getMostPopulatedCourseCount('ASC')}" />
                    
                    <h:outputText value="Antal kurser på svenska" />
                    <h:outputText value="#{courseManagedBean.getByLanguage(1)}" />
                    
                    <h:outputText value="Antal studenter i svenska kurser" />
                    <h:outputText value="#{studentManagedBean.getStudentCountByCourseLanguage('Svenska')}" />
                    
                    <h:outputText value="Antal kurser på engelska" />
                    <h:outputText value="#{courseManagedBean.getByLanguage(0)}" />
                    
                    <h:outputText value="Antal studenter i engelska kurser" />
                    <h:outputText value="#{studentManagedBean.getStudentCountByCourseLanguage('Engelska')}" />
                    
                    <h:outputText value="Kurser på grundnivå" />
                    <h:outputText value="#{courseManagedBean.getCourseCountByLevel('Grundnivå')}" />
                    
                    <h:outputText value="Kurser på avancerad nivå" />
                    <h:outputText value="#{courseManagedBean.getCourseCountByLevel('Avancerad')}" />

                </p:panelGrid>

            </p:layoutUnit>
        </p:layout>
    </h:body>
</html>

attendance-war/web/student.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f='http://java.sun.com/jsf/core'
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Studenter</title>
    </h:head>
    <h:body>
        <ui:include src="header.xhtml"/><br></br>

        <!-- Register form -->
        <p:layout id="layout" styleClass="reg-student-layout">
            <p:layoutUnit id="layoutRegister" position="west" resizable="false" size="215">
                <h:form id="registerForm" style="margin-left: 5px;">
                    <br/><p:outputLabel class="ui-state-default" style="font-size: 18px; padding: 5px;" value="Registrera ny student"/>
                    <br/>
                    <br/><h:outputText value="Förnamn" styleClass="form_label"/><h:message for="first_name" styleClass="error"/>
                    <br><p:inputText style="margin: auto;" id="first_name" value="#{studentManagedBean.student.firstName}"/></br>

                    <h:outputText value="Efternamn" styleClass="form_label"/><h:message for="last_name" styleClass="error" />
                    <br><p:inputText style="margin: auto;" id="last_name" value="#{studentManagedBean.student.lastName}"/></br>

                    <h:outputText value="Telefon" styleClass="form_label"/><h:message for="tel_number" styleClass="error" />
                    <br><p:inputText style="margin: auto;" id="tel_number" value="#{studentManagedBean.student.phoneNumber}"/></br>

                    <h:outputText value="Adress" styleClass="form_label"/><h:message for="address" styleClass="error" />
                    <br><p:inputText style="margin: auto;" id="address" value="#{studentManagedBean.student.address}"/></br>

                    <h:outputText value="Email" styleClass="form_label"/><h:message for="email" styleClass="error" />
                    <br><p:inputText style="margin: auto;" id="email" value="#{studentManagedBean.student.email}"/></br>

                    <h:outputText value="Start Date" styleClass="form_label"/><h:message for="start_date" styleClass="error" /><br/>
                    <p:calendar id="start_date" value="#{studentManagedBean.student.startDate}" pattern="dd-MM-yyyy" /><br/>

                    <br><p:commandButton id="submit" value="Skapa Student" update="registerForm, :tableForm:dataTable"
                                         actionListener="#{studentManagedBean.createStudent()}"
                                         style="width: 95%;"/></br>
                </h:form>
            </p:layoutUnit>

            <!-- Output Table -->
            <p:layoutUnit id="layoutTable" position="center">
                <h:form style="margin-left: 5px;" id="tableForm">
                    <p:dataTable id="dataTable" value="#{studentManagedBean.getStudents()}" 
                                 var="std" >

                        <p:column>
                            <f:facet name="header">Förnamn</f:facet>
                            <p:outputLabel value="#{std.firstName}"/>
                        </p:column>

                        <p:column>
                            <f:facet name="header">Efternamn</f:facet>
                            <p:outputLabel value="#{std.lastName}"/>
                        </p:column>

                        <p:column style="width: 85px; text-align: center;">
                            <f:facet name="header">Telefon</f:facet>
                            <p:outputLabel value="#{std.phoneNumber}"/>
                        </p:column>

                        <p:column style="width: 290px">
                            <f:facet name="header">Adress</f:facet>
                            <p:outputLabel value="#{std.address}"/>
                        </p:column>

                        <p:column style="width: 200px; text-align: center;">
                            <f:facet name="header">Email</f:facet>
                            <p:outputLabel value="#{std.email}"/>
                        </p:column>

                        <p:column style="width: 85px; text-align: center;">
                            <f:facet name="header">Registrerad</f:facet>
                            <p:outputLabel  value="#{std.startDate}">
                                <f:convertDateTime pattern="dd-MM-yyyy"/>
                            </p:outputLabel>
                        </p:column>

                        <p:column style="width: 25px">
                            <f:facet name="header">Info</f:facet>
                            <p:commandLink value="info" type="button" 
                                           action="#{studentManagedBean.setStudent(std)}"
                                           update=":info" oncomplete="PF('info').show();"/>
                        </p:column>

                        <p:column style="width: 25px">
                            <f:facet name="header">Edit</f:facet>
                            <p:commandLink value="edit" type="button" 
                                           action="#{studentManagedBean.getDualListModelForStudent(std)}"
                                           update=":update" oncomplete="PF('update').show();"/>
                        </p:column>

                        <p:column style="width: 55px; text-align: center">
                            <f:facet name="header">Ta bort</f:facet>
                            <p:commandLink value="delete" update="@form" 
                                           action="#{studentManagedBean.deleteStudent(std)}"/>
                        </p:column>
                    </p:dataTable>
                </h:form>
            </p:layoutUnit>

            <!-- STUDENT UPDATE DIALOG -->
            <p:dialog id="update" closable="false" header="Updatera Student" widgetVar="update" modal="true" width="490" height="100%" visible="#{facesContext.validationFailed}">
                <h:form id="updateForm">                    
                    <h:outputText value="Förnamn" styleClass="form_label"/><h:message for="f_name" styleClass="error"/>
                    <br><p:inputText style="margin: auto; width: 98%" id="f_name" value="#{studentManagedBean.student.firstName}"/></br>

                    <h:outputText value="Efternamn" styleClass="form_label"/><h:message for="l_name" styleClass="error" />
                    <br><p:inputText style="margin: auto; width: 98%" id="l_name" value="#{studentManagedBean.student.lastName}"/></br>

                    <h:outputText value="Telefon" styleClass="form_label"/><h:message for="t_number" styleClass="error" />
                    <br><p:inputText style="margin: auto; width: 98%" id="t_number" value="#{studentManagedBean.student.phoneNumber}"/></br>

                    <h:outputText value="Adress" styleClass="form_label"/><h:message for="addres" styleClass="error" />
                    <br><p:inputText style="margin: auto; width: 98%" id="addres" value="#{studentManagedBean.student.address}"/></br>

                    <h:outputText value="Email" styleClass="form_label"/><h:message for="e-mail" styleClass="error" />
                    <br><p:inputText style="margin: auto; width: 98%" id="e-mail" value="#{studentManagedBean.student.email}"/></br>

                    
                    <!-- STUDENT'S COURSE LIST -->
                    <br/><h4 style="margin-top: 0">Students kurs List</h4>
                    
                    <p:pickList id="pickList" value="#{studentManagedBean.courses}" var="courses" itemLabel="#{courses}" itemValue="#{courses}" />

                    <p:dialog modal="true" showEffect="fade" hideEffect="fade" widgetVar="courseDialog">
                        <h:panelGrid id="displayCourses" columns="2">
                            <h:outputText value="Source: " style="font-weight:bold" />
                             <ui:repeat value="#{studentManagedBean.courses.source}" var="item">
                                <h:outputText value="#{item}" style="margin-right:5px" />
                            </ui:repeat>

                            <h:outputText value="Target: " style="font-weight:bold" />
                            <ui:repeat value="#{studentManagedBean.courses.target}" var="item">
                                <h:outputText value="#{item}" style="margin-right:5px" />
                            </ui:repeat>
                        </h:panelGrid>
                    </p:dialog>
                    
                    <!-- ACTION BUTTONS OF UPDATE DIALOG -->
                    <br><p:commandButton id="cancelButton" value="Stäng" 
                                         action="#{studentManagedBean.closePopup()}"  style="width: 45%;"
                                         onclick="editDialog.hide()" />
                        
                    <p:commandButton id="updateButton" value="Updatera" update="displayCourses, :tableForm:dataTable"
                                     oncomplete="PF('courseDialog').show()"
                                     action="#{studentManagedBean.updateStudent()}"  style="width: 45%;  float: right;"
                                     onclick="if (args &amp; &amp; !args.validationFailed) editDialog.hide()" /></br>
                </h:form>
            </p:dialog>

            <!-- STUDENT DETAILS DIALOG -->
            <p:dialog id="info" closable="false" header="Student detaljer" widgetVar="info" modal="true" width="400" height="420">
                <h:form id="infoForm">   
                    <h:outputText value="Förnamn" styleClass="form_label"/>
                    <br><p:outputLabel class="info" id="f_name" value="#{studentManagedBean.student.firstName}"/></br>

                    <h:outputText value="Efternamn" styleClass="form_label"/>
                    <br><p:outputLabel class="info" id="l_name" value="#{studentManagedBean.student.lastName}"/></br>

                    <h:outputText value="Telefon" styleClass="form_label"/>
                    <br><p:outputLabel class="info" id="t_number" value="#{studentManagedBean.student.phoneNumber}"/></br>

                    <h:outputText value="Adress" styleClass="form_label"/>
                    <br><p:outputLabel class="info" id="addres" value="#{studentManagedBean.student.address}"/></br>

                    <h:outputText value="Email" styleClass="form_label"/>
                    <br><p:outputLabel class="info" id="e-mail" value="#{studentManagedBean.student.email}"/></br>

                    <h:outputText value="Start Date" styleClass="form_label"/><br/>
                    <p:outputLabel class="info" id="startdate" value="#{studentManagedBean.student.startDate}">
                        <f:convertDateTime pattern="yyyy-MM-dd"/>
                    </p:outputLabel><br/><br/>
                    
                    <p:dataTable id="dataTable" rendered="#{studentManagedBean.student.id != 0}" 
                                 value="#{studentManagedBean.getCourseListByStudentId(studentManagedBean.student.id)}" var="course">
                        <p:column>
                            <f:facet name="header">Students Kurs Lista</f:facet>
                            <p:outputLabel value="#{course.courseName}"/>
                        </p:column>
                    </p:dataTable>

                    <br/><p:commandButton id="close" value="Stäng" style="width: 100%" onclick="info.hide()"
                                          action="#{studentManagedBean.closePopup()}" />
                </h:form>
            </p:dialog>
        </p:layout>
    </h:body>
</html>